import { useEffect, useMemo, useRef, useState } from 'react';
import { toPng } from 'html-to-image';
import { createRoot } from 'react-dom/client';
import { formatPlaytime, parseSteamProfileInput, steamArtworkUrl } from './steam';
import { loadState, makeState, moveGames } from './tierState';
import type { Game, TierState } from './types';
import './styles.css';

const api=(import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/,'');
type Sort='az'|'za'|'most'|'least'|'recent'; type Filter='all'|'played'|'never';
function GameCard({game,selected,onClick,onDragStart}:{game:Game;selected:boolean;onClick:(e:React.MouseEvent)=>void;onDragStart:(e:React.DragEvent)=>void}) { const [bad,setBad]=useState(false); return <button className={`game-card ${selected?'selected':''}`} draggable onClick={onClick} onDragStart={onDragStart} title={`${game.name} — ${formatPlaytime(game.playtimeForever)}`} aria-label={`Drag ${game.name}`}><img loading="lazy" src={bad?'https://cdn.akamai.steamstatic.com/steam/apps/0/header.jpg':steamArtworkUrl(game.appid)} alt={game.name} onError={()=>setBad(true)}/><span>{game.name}</span></button> }
function App(){ const [profile,setProfile]=useState(''); const [games,setGames]=useState<Game[]>([]); const [state,setState]=useState<TierState|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [search,setSearch]=useState(''); const [sort,setSort]=useState<Sort>('az'); const [filter,setFilter]=useState<Filter>('all'); const [selected,setSelected]=useState<Set<number>>(new Set()); const [history,setHistory]=useState<TierState[]>([]); const board=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(state) localStorage.setItem(`steam-tier-list:${state.steamId}`,JSON.stringify(state));},[state]);
 const byId=useMemo(()=>new Map(games.map(g=>[g.appid,g])),[games]);
 const unranked=useMemo(()=>state?.unranked.map(id=>byId.get(id)).filter((g):g is Game=>!!g).filter(g=>(filter==='all'||filter==='played'?g.playtimeForever>0:g.playtimeForever===0)&&g.name.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='az'?a.name.localeCompare(b.name):sort==='za'?b.name.localeCompare(a.name):sort==='most'?b.playtimeForever-a.playtimeForever:sort==='least'?a.playtimeForever-b.playtimeForever:(b.playtime2Weeks||0)-(a.playtime2Weeks||0))||[],[state,byId,filter,search,sort]);
 async function load(){const parsed=parseSteamProfileInput(profile);if(!parsed){setError('Please enter a valid Steam profile URL, vanity name, or SteamID64.');return} if(!api){setError('This site has not been connected to its library service yet.');return} setLoading(true);setError('');try{const r=await fetch(`${api}/api/library?profile=${encodeURIComponent(profile.trim())}`);const data=await r.json();if(!r.ok) throw new Error(data.error||'Steam is temporarily unavailable. Please try again.');if(!data.games?.length) throw new Error('No publicly visible games were found for this Steam profile.');setGames(data.games);setState(loadState(data.steamId,data.games.map((g:Game)=>g.appid)));setSelected(new Set());}catch(e){console.error(e);setError(e instanceof Error?e.message:'Steam is temporarily unavailable. Please try again.')}finally{setLoading(false)}}
 function move(ids:number[],dest:string,index?:number){if(!state)return;setHistory(h=>[state,...h].slice(0,40));setState(moveGames(state,ids,dest,index));setSelected(new Set());}
 function drag(e:React.DragEvent,id:number){const ids=selected.has(id)?[...selected]:[id];e.dataTransfer.setData('gameIds',JSON.stringify(ids));e.dataTransfer.effectAllowed='move'} function drop(e:React.DragEvent,dest:string){e.preventDefault();try{move(JSON.parse(e.dataTransfer.getData('gameIds')),dest)}catch{}}
 function cards(ids:number[]){return ids.map(id=>{const g=byId.get(id);return g&&<GameCard key={id} game={g} selected={selected.has(id)} onDragStart={e=>drag(e,id)} onClick={e=>setSelected(prev=>{const next=new Set(e.ctrlKey||e.metaKey?prev:[]);next.has(id)?next.delete(id):next.add(id);return next})}/>})}
 async function exportPng(){if(!board.current)return;if(games.length>1500&&!confirm('Exporting a very large tier list can be slow. Continue?'))return;try{const data=await toPng(board.current,{cacheBust:true,pixelRatio:1});const a=document.createElement('a');a.href=data;a.download='steam-tier-list.png';a.click()}catch(e){console.error(e);setError('Could not export this tier list. Try reducing the number of ranked games.')}}
 function undo(){if(!history.length)return;const [previous,...rest]=history;setState(previous);setHistory(rest)}
 const reset=()=>{if(state&&confirm('Reset all tier assignments for this profile?')){setHistory(h=>[state,...h]);setState(makeState(state.steamId,games.map(g=>g.appid)))}};
 if(!state)return <main className="welcome"><section><p className="eyebrow">PUBLIC LIBRARY ORGANIZER</p><h1>Steam Library<br/><em>Tier List</em></h1><p>Paste a public Steam profile URL, vanity name, or SteamID64 to rank your library. Your Steam profile and Game Details must be public.</p><label htmlFor="profile">Steam profile</label><div className="load-row"><input id="profile" value={profile} onChange={e=>setProfile(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="https://steamcommunity.com/id/yourname"/><button onClick={load} disabled={loading}>{loading?'Loading library…':'Load Library'}</button></div>{error&&<p className="error" role="alert">{error}</p>}<small>No sign-in required. Your ranking stays in this browser.</small></section></main>;
 return <main onClick={e=>{if(e.target===e.currentTarget)setSelected(new Set())}}><header><div><p className="eyebrow">{games.length.toLocaleString()} GAMES LOADED</p><h1>Steam Library Tier List</h1></div><div className="actions"><button onClick={undo} disabled={!history.length}>Undo</button><button onClick={reset}>Reset</button><button onClick={()=>{if(confirm('Clear saved progress for this profile?')){localStorage.removeItem(`steam-tier-list:${state.steamId}`);setState(makeState(state.steamId,games.map(g=>g.appid)))}}}>Clear saved</button><button className="primary" onClick={exportPng}>Export PNG</button></div></header><div className="tip">Tip: Ctrl/Cmd-click cards to select several, then drag one of them together.</div><section className="board" ref={board}>{state.tiers.map(t=><div className="tier-row" key={t.id}><div className="tier-label">{t.label}</div><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,t.id)}>{cards(t.gameIds)}</div></div>)}<div className="tier-row na"><div className="tier-label">N/A</div><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,'notRanking')}>{cards(state.notRanking)}</div></div></section><section className="library"><div className="library-head"><div><h2>Unranked</h2><p>{unranked.length} visible · {state.unranked.length} unranked · {games.length} total</p></div><div className="controls"><input aria-label="Search unranked games" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search games"/><select value={filter} onChange={e=>setFilter(e.target.value as Filter)}><option value="all">All games</option><option value="played">Played</option><option value="never">Never played</option></select><select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="az">A–Z</option><option value="za">Z–A</option><option value="most">Most played</option><option value="least">Least played</option><option value="recent">Recently played</option></select></div></div><div className="pool" onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,'unranked')}>{unranked.map(g=><GameCard key={g.appid} game={g} selected={selected.has(g.appid)} onDragStart={e=>drag(e,g.appid)} onClick={e=>setSelected(prev=>{const n=new Set(e.ctrlKey||e.metaKey?prev:[]);n.has(g.appid)?n.delete(g.appid):n.add(g.appid);return n})}/>)}</div></section></main> }
createRoot(document.getElementById('root')!).render(<App/>);
